EXCEL_HEADERS = [
    "Offer Priority",
    "Offer Type",
    "Bonus Offer / Starburst / Offer Emphasis",
    "Vehicle Type",
    "Year",
    "Make",
    "Model",
    "Trim",
    "Drive Train",
    "Stock Number",
    "VIN Number",
    "MSRP",
    "Lowest Monthly Payment",
    "Lease Term/Months",
    "Down Payment or Due at Signing",
    "Down Payment",
    "Total Due at Signing",
    "Annual Mileage",
    "Finance Rate",
    "Finance Term/Months",
    "Discount Towards MSRP",
    "Buy For Price",
    "Selling Price",
    "Disclaimer",
    "Additional Creative Needs",
    "Impel Model Movers",
]

EXCEL_FIELD_ORDER = [
    "offer_priority",
    "offer_type",
    "offer_emphasis",
    "vehicle_type",
    "year",
    "make",
    "model",
    "trim",
    "drive_train",
    "stock_number",
    "vin_number",
    "msrp",
    "lowest_monthly_payment",
    "lease_term_months",
    "down_payment_or_due_at_signing",
    "down_payment",
    "total_due_at_signing",
    "annual_mileage",
    "finance_rate",
    "finance_term_months",
    "discount_towards_msrp",
    "buy_for_price",
    "selling_price",
    "disclaimer",
    "additional_creative_needs",
    "impel_model_movers",
]

OFFER_TYPE_OPTIONS = [
    "Lease Offer",
    "Combined Lease/APR Offer",
    "Bonus Cash Offer",
    "Buy For Offer",
    "Finance Offer",
    "Bonus Offer",
    "Conquest Offer",
]

VEHICLE_TYPE_OPTIONS = [
    "New",
    "Used",
    "CPO",
    "Loaner/Courtesy Vehicle/Nearly New",
]

PAYMENT_TYPE_OPTIONS = [
    "Down Payment",
    "Due at Signing",
]
